sudo: true
language: generic

git:
  depth: 5

cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - os: linux
  - os: osx

install:
  # HLint check
  - curl https://raw.githubusercontent.com/kowainik/relude/v0.6.0.0/.hlint.yaml -o .hlint-relude.yaml
  - curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s src/ test/ -h .hlint-relude.yaml

  # install stack and build project
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version
  - stack build --test --no-run-tests --bench --no-run-benchmarks

script:
  - stack test --no-terminal

after_success:
  - echo "Trying to deploy..."
  - cd "$TRAVIS_BUILD_DIR"
  - mv "$(stack path --local-install-root)/bin/life" "life-${TRAVIS_OS_NAME}"
  - chmod +x "life-${TRAVIS_OS_NAME}"

deploy:
  - skip_cleanup: true
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - "life-${TRAVIS_OS_NAME}"
    on:
      repo: kowainik/life-sync
      tags: true

notifications:
  email: false
